In [10]:
import numpy as np
from ncon import ncon as nc


# Tensors initialization

In [6]:
i= 1
j= 2
k= 3

a= 4
b= 5
c= 6
d= 7 
e= 8
f= 9
h= 10

A = np.random.uniform(-1, 1, (i, b, a))
B = np.random.uniform(-1, 1, (b, k, c, e))
C = np.random.uniform(-1, 1, (a, c, d, h))
D = np.random.uniform(-1, 1, (j, d, f))
E = np.random.uniform(-1, 1, (f, h, e))

# Manual contraction

In [8]:
def Manual_contraction(A, B, C, D, E):

    AB = np.zeros((i, k, a, c, e))
    ABC = np.zeros((i, k, d, h, e))
    ABCE = np.zeros((i, k, j, d, f))
    ABCED = np.zeros((i, k, j))

    for i_ in range(i):
        for k_ in range(k):
            for a_ in range(a):
                for c_ in range(c):
                    for e_ in range(e):
                        for b_ in range(b):
                            AB[i_, k_, a_, c_, e_] += A[i_, b_, a_]*B[b_, k_, c_, e_]

    for i_ in range(i):
        for k_ in range(k):
            for d_ in range(d):
                for h_ in range(h):
                    for e_ in range(e):
                        for a_ in range(a):
                            for c_ in range(c):
                                ABC[i_, k_, d_, h_, e_] += AB[i_, k_, a_, c_, e_]*C[a_, c_, d_, h_]


    for i_ in range(i):
        for k_ in range(k):
            for j_ in range(j):
                for d_ in range(d):
                    for f_ in range(f):
                        for h_ in range(h):
                            for e_ in range(e):
                                ABCE[i_, k_, j_, d_, f_] += ABC[i_, k_, d_, h_, e_]*E[f_, h_, e_]

    for i_ in range(i):
        for k_ in range(k):
            for j_ in range(j):
                for d_ in range(d):
                    for f_ in range(f):
                        ABCED[i_, k_, j_] += ABCE[i_, k_, j_, d_, f_]*D[j_, d_, f_]

    return ABCED

    
Manual_contraction(A, B, C, D, E)

array([[[  2.57975995, -17.22821835],
        [ 59.11512873, -30.00855828],
        [ 22.49169203, -15.04234221]]])

# Numpy contraction

In [19]:
# A = np.random.uniform(-1, 1, (i, b, a))
# B = np.random.uniform(-1, 1, (b, k, c, e))
# C = np.random.uniform(-1, 1, (a, c, d, h))
# D = np.random.uniform(-1, 1, (j, d, f))
# E = np.random.uniform(-1, 1, (f, h, e))

# AB = np.zeros((i, k, a, c, e))
# ABC = np.zeros((i, k, d, h, e))
# ABCE = np.zeros((i, k, j, d, f))
# ABCED = np.zeros((i, k, j))

def np_contraction(A, B, C, D, E):

    AB = np.tensordot(A, B, axes=[[1],[0]])
    print(AB.shape, C.shape)
    ABC = np.tensordot(AB, C, axes=[[1, 3], [0, 1]])
    print(ABC.shape, E.shape)
    ABCE = np.tensordot(ABC, E, axes=[[2, -1], [-1, -2]])
    print(ABCE.shape, D.shape)
    ABCED = np.tensordot(ABCE, D, axes=[[-2, -1], [-2, -1]])

    return ABCED

np_contraction(A, B, C, D, E)

(1, 4, 3, 6, 8) (4, 6, 7, 10)
(1, 3, 8, 7, 10) (9, 10, 8)
(1, 3, 7, 9) (2, 7, 9)


array([[[-32.56521986,  26.55490016],
        [ 81.55107259,  34.28103959],
        [-44.95151289,   4.9604763 ]]])

# Ncon contraction

In [11]:
# A = np.random.uniform(-1, 1, (i, b, a))
# B = np.random.uniform(-1, 1, (b, k, c, e))
# C = np.random.uniform(-1, 1, (a, c, d, h))
# D = np.random.uniform(-1, 1, (j, d, f))
# E = np.random.uniform(-1, 1, (f, h, e))


nc(
    [A, B, C, D, E],
    [
        # i, b, a
        [-1, 1, 2],
        # b, k, c, e
        [1, -3, 3, 4],
        # a, c, d, h
        [2, 3, 5, 6],
        # j, d, f
        [-2, 5, 7],
        # f, h, e
        [7, 6, 4]
    ]
)

array([[[-32.56521986,  81.55107259, -44.95151289],
        [ 26.55490016,  34.28103959,   4.9604763 ]]])