# Домашняя работа<br/>
Выполнил студент: Чистов Виктор <br/>
<br/>
Задание: выполнить свертку пяти тензоров, тремя разными способами.
Через цикл for, с помощью библиотеки numpy, с помощью библиотеки ncon.

In [32]:
import numpy as np
import time
from ncon import ncon

Создадим тензоры

In [33]:
x = 5
a = np.random.rand(x,x,x)
b = np.random.rand(x,x,x,x)
c = np.random.rand(x,x,x,x)
d = np.random.rand(x,x,x)
e = np.random.rand(x,x,x)

Библиотека ncon

In [34]:
def nconn(a, b, c, d, e):
  return ncon((a, b, c, d, e), ([-1, 1, 5], [1, 6, 2, -2], [5, 6, 4, 7], [3, 4, -3], [2, 7, 3]))

In [35]:
print(nconn(a,b,c,d,e))
print(nconn(a,b,c,d,e).shape)

[[[3517.28180537 2917.79499814 3524.47078971 3826.16437738 2991.76036053]
  [3617.69374696 3002.78848021 3626.1193271  3938.9055346  3087.38034884]
  [3650.25861869 3028.72580101 3658.53097867 3977.20741191 3102.31202722]
  [3472.01448582 2881.35037959 3482.88007156 3782.17621784 2952.24348606]
  [3539.18242788 2934.94822214 3547.65893609 3857.43463836 3009.15327484]]

 [[3135.6086166  2602.13885265 3145.25071427 3415.69596328 2676.51131991]
  [3244.23251365 2692.79282923 3254.17315363 3536.53572165 2772.99216247]
  [3223.62473218 2674.32103651 3232.49928888 3515.86205192 2743.98539992]
  [3098.36345947 2571.65423995 3109.88570466 3377.37226284 2642.95394673]
  [3147.03373284 2609.23501312 3154.84972989 3432.84049328 2681.23370652]]

 [[3624.67383672 3005.3945224  3636.49121655 3947.1558955  3094.36550676]
  [3699.08576296 3066.67570508 3708.94342562 4026.54806567 3158.92624285]
  [3688.67741063 3055.87556436 3698.84596315 4017.3386868  3134.68497786]
  [3610.3288379  2994.31086636 362

Библиотека Numpy

In [36]:
def RSH(a, b, c, d, e):
    AC = np.tensordot(a, c, axes=([2],[0]))
    ACB = np.tensordot(AC, b, axes=([1,2],[0,1]))
    ACBE = np.tensordot(ACB, e, axes=([2,3],[1,0]))
    return np.tensordot(ACBE, d, axes=([1,2],[1,2]))

In [37]:
print(RSH(a,b,c,d,e))
print(RSH(a,b,c,d,e).shape)

[[[3212.20405362 3572.32520608 2700.13881247 3087.39230822 3952.49743566]
  [3193.69219115 3548.46999676 2687.688811   3073.37077489 3927.54936806]
  [3084.28417287 3423.02859897 2592.93977043 2964.87203196 3795.24402229]
  [3375.27527382 3747.71289735 2841.73353106 3244.61913832 4145.27656895]
  [3558.73691615 3958.78857346 2990.23405737 3419.15079752 4371.69779778]]

 [[2871.67995829 3195.89935838 2405.03741703 2756.24366984 3526.83627449]
  [2849.11714373 3166.74694213 2386.19334658 2736.75852906 3493.81988227]
  [2747.99361665 3052.04410269 2300.91380318 2637.36085581 3373.80940589]
  [3014.1733558  3347.31110968 2526.24731095 2892.83084678 3694.5944008 ]
  [3172.92993702 3527.13493177 2653.89500933 3041.66691527 3887.33515368]]

 [[3304.12453785 3682.29503221 2768.35294762 3175.09179343 4064.61078186]
  [3282.20577595 3652.93189526 2753.71789592 3157.89260477 4033.08321302]
  [3174.36229918 3529.86124204 2663.10191383 3050.96242304 3903.98907346]
  [3474.21060812 3865.71961351 291

Цикл for

In [38]:
def forr(a,b,c,d,e,x):
    ac = np.zeros((x, x, x, x, x))
    for i in range(x):
        for j in range(x):
            for k in range(x):
                for l in range(x):
                    for m in range(x):
                        for n in range(x): 
                            ac[i, j, k, l, m] = ac[i, j, k, l, m] + a[i, j, n] * c[n, k, l, m]
    acb = np.zeros((x, x, x, x, x))
    for i in range(x):
        for j in range(x):
            for k in range(x):
                for l in range(x):
                    for m in range(x):
                        for n in range(x):
                            for p in range(x):  
                                acb[i, j, k, l, m] = acb[i, j, k, l, m] + ac[i, n, p, j, k] * b[n, p, m, l]
    acbe = np.zeros((x, x, x, x))
    for i in range(x):
        for j in range(x):
            for k in range(x):
                for l in range(x):
                    for m in range(x):
                        for n in range(x):
                            acbe[i, j, k, l] = acbe[i, j, k, l] + acb[i, j, m, k, n] * e[n, m, l]
    acbed  = np.zeros((x, x, x))
    for i in range(x):
        for j in range(x):
            for k in range(x):
                for l in range(x):
                    for m in range(x):
                        acbed[i, j, k] =  acbed[i, j, k] + acbe[i, l, j, m] + d[m, l, k]
    return acbed

In [39]:
print(forr(a,b,c,d,e,x))
print(forr(a,b,c,d,e,x).shape)

[[[6525.81307977 6523.47847806 6525.80041804 6527.02917067 6523.72274788]
  [6719.96871516 6717.63411344 6719.95605342 6721.18480605 6717.87838326]
  [6778.69867248 6776.36407077 6778.68601075 6779.91476338 6776.60834059]
  [6450.14329334 6447.80869162 6450.1306316  6451.35938423 6448.05296144]
  [6570.68804092 6568.35343921 6570.67537919 6571.90413181 6568.59770903]]

 [[5822.98178175 5820.64718004 5822.96912002 5824.19787265 5820.89144986]
  [6031.31518171 6028.98058    6031.30251998 6032.53127261 6029.22484982]
  [5990.20034653 5987.86574481 5990.18768479 5991.41643742 5988.11001463]
  [5758.89240123 5756.55779952 5758.8797395  5760.10849213 5756.80206934]
  [5845.10809033 5842.77348862 5845.0954286  5846.32418123 5843.01775844]]

 [[6728.8047822  6726.47018048 6728.79212046 6730.02087309 6726.7144503 ]
  [6868.67627112 6866.34166941 6868.66360939 6869.89236201 6866.58593923]
  [6845.6827856  6843.34818388 6845.67012387 6846.89887649 6843.5924537 ]
  [6707.03499263 6704.70039092 670

Замер времени

In [40]:
start = time.time()
nconn(a,b,c,d,e)
end = time.time() - start
print(f"Время выполнения с помощью библиотеки ncon = {end}")

start = time.time()
RSH(a,b,c,d,e)
end = time.time() - start
print(f"Время выполнения с помощью библиотеки numpy = {end}")

start = time.time()
forr(a,b,c,d,e,x)
end = time.time() - start
print(f"Время выполнения через цикл for = {end}")

Время выполнения с помощью библиотеки ncon = 0.0009999275207519531
Время выполнения с помощью библиотеки numpy = 0.0009980201721191406
Время выполнения через цикл for = 0.09800076484680176


# Вывод. <br/>
Операция свертки через цикл for самая долгая и объемная по коду.<br/>
С помощью библиотеки numpy самая быстрая.<br/>
С помощью библиотеки ncon самая простая в написании по коду и быстее выполняется, чем через цикл for.