In [ ]:
!pip install  ncon

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
from ncon import ncon
import time

# Лабораторная №1

Задание изнальных тензоров

In [ ]:
A = np.random.rand(10, 10, 10)
B = np.random.rand(10, 10, 10, 10)
C = np.random.rand(10, 10, 10, 10)
E = np.random.rand(10, 10, 10)
D = np.random.rand(10, 10, 10)

1. Свертка циклами for

In [ ]:
def ConvFor(A, B, C, D, E):
    AC = np.zeros((10, 10, 10, 10, 10))
    for i in range(10):
        for j in range(10):
            for k in range(10):
                for l in range(10):
                    for m in range(10):
                        for n in range(10): 
                            AC[i, j, k, l, m] = AC[i, j, k, l, m] + A[i, j, n] * C[n, k, l, m]
    ACB = np.zeros((10, 10, 10, 10, 10))
    for i in range(10):
        for j in range(10):
            for k in range(10):
                for l in range(10):
                    for m in range(10):
                        for n in range(10):
                            for p in range(10):  
                                ACB[i, j, k, l, m] = ACB[i, j, k, l, m] + AC[i, n, p, j, k] * B[n, p, m, l]
    ACBE = np.zeros((10, 10, 10, 10))
    for i in range(10):
        for j in range(10):
            for k in range(10):
                for l in range(10):
                    for m in range(10):
                        for n in range(10):
                            ACBE[i, j, k, l] = ACBE[i, j, k, l] + ACB[i, j, m, k, n] * E[n, m, l]
    result  = np.zeros((10, 10, 10))
    for i in range(10):
        for j in range(10):
            for k in range(10):
                for l in range(10):
                    for m in range(10):
                        result[i, j, k] =  result[i, j, k] + ACBE[i, l, j, m] + D[m, l, k]
    return result

In [ ]:
%%timeit
result = ConvFor(A, B, C, D, E)

9.11 s ± 540 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
ConvFor(A, B, C, D, E)

array([[[572287.70125099, 572282.8552891 , 572286.32242224,
         572284.64618166, 572283.9965339 , 572284.94547706,
         572284.44910227, 572281.30134269, 572288.43648974,
         572286.49887058],
        [567909.10636256, 567904.26040068, 567907.72753381,
         567906.05129323, 567905.40164547, 567906.35058863,
         567905.85421385, 567902.70645426, 567909.84160131,
         567907.90398216],
        [562831.39268145, 562826.54671956, 562830.0138527 ,
         562828.33761212, 562827.68796436, 562828.63690752,
         562828.14053273, 562824.99277315, 562832.1279202 ,
         562830.19030104],
        [578401.82788883, 578396.98192694, 578400.44906008,
         578398.7728195 , 578398.12317174, 578399.0721149 ,
         578398.57574011, 578395.42798053, 578402.56312758,
         578400.62550842],
        [556346.61298235, 556341.76702047, 556345.2341536 ,
         556343.55791302, 556342.90826526, 556343.85720842,
         556343.36083364, 556340.21307405, 556347.34

2. Свертка при помощи reshape и @

In [ ]:
def ConvReshape(A, B, C, D, E):
    AC = np.tensordot(A, C, axes=([2],[0]))
    ACB = np.tensordot(AC, B, axes=([1,2],[0,1]))
    ACBE = np.tensordot(ACB, E, axes=([2,3],[1,0]))
    return np.tensordot(ACBE, D, axes=([1,2],[1,2]))

In [ ]:
%%timeit
result = ConvReshape(A, B, C, D, E)

2.03 ms ± 185 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
ConvReshape(A, B, C, D, E)

array([[[298358.22039424, 295790.70206465, 275330.78854541,
         272304.6762405 , 299403.24967101, 291610.0369258 ,
         285933.04477942, 273249.16705168, 295812.91094933,
         269160.93935508],
        [275687.94929008, 273406.46494299, 254577.89022473,
         251760.01426264, 276763.63734538, 269503.8156371 ,
         264212.77753252, 252458.50148711, 273467.67352432,
         248929.03699767],
        [295659.08491024, 293125.30021054, 273047.89822078,
         269934.62871381, 296716.42400462, 288862.94823378,
         283241.16203372, 270665.69018117, 293243.37406559,
         266718.44816551],
        [321120.52227751, 318478.86162326, 296615.14438447,
         293161.90384468, 322368.49494842, 313839.61965319,
         307749.80359013, 293932.40653206, 318471.37767599,
         289926.78052981],
        [301903.09194383, 299398.63323613, 278756.48045411,
         275568.75504786, 303117.41265415, 294968.69900267,
         289281.64410433, 276489.27383268, 299397.66

3. Свертка ncon

In [ ]:
def ConvNcon(A, B, C, D, E):
  return ncon((A, B, C, D, E), ([-1, 1, 5], [1, 6, 2, -2], [5, 6, 4, 7], [3, 4, -3], [2, 7, 3]))

In [ ]:
%%timeit
result = ConvNcon(A, B, C, D, E)

50.7 ms ± 2.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
ConvNcon(A, B, C, D, E)

array([[[304874.7250434 , 276915.47103466, 298973.6797717 ,
         288522.70057629, 283889.99083377, 289484.01385538,
         285978.25579534, 268305.42081529, 310405.66986293,
         299589.38613545],
        [302611.23829814, 274768.51016275, 296731.37889882,
         286356.09575259, 281809.09272593, 287301.12225387,
         283725.82516044, 266277.60829122, 308020.6250284 ,
         297309.56030083],
        [299881.50219426, 272316.01073711, 294014.62736061,
         283793.96952496, 279252.92558968, 284699.60827198,
         281276.30774461, 263857.69078417, 305280.89521223,
         294583.16209271],
        [308096.96919544, 279903.10760624, 302149.983834  ,
         291589.38060849, 286810.90840716, 292600.01525182,
         289046.20437169, 271201.872345  , 313701.68180215,
         302856.60501283],
        [296361.60479454, 269225.60675436, 290620.34558163,
         280459.45856718, 276050.66469655, 281404.75566035,
         277998.99685908, 260880.45953262, 301720.42

# Топ по скорости выполнения:

1. reshpe + @

2. ncon

3. for